name: "Build font and deploy page"

on: push

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build_and_deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt install python3 python3-pip woff2 -y
          pip3 install -r ./requirements.txt
      - name: Build font
        run: |
          cd src
          ./build_without_venv.sh
      - name: Upload font
        uses: actions/upload-artifact@v4
        with:
          name: "Font files"
          path: dist
      - name: Page upload preparations
        run: |
          mv dist/* page/
      - name: Upload page
        uses: actions/upload-pages-artifact@v3
        with:
          path: page
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

